version: '3.4'

services:
  api:
    image: librarymanagementapi
    restart: always
    build:
      context: .
      dockerfile: ./DockerFile
    env_file:
      - ./.env
    ports:
      - 8000:8000

  postgres:
    image: postgres
    container_name: postgres-library
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: assayag.meir@gmail.com
      PGADMIN_DEFAULT_PASSWORD: mongodb?
    ports:
      - 8080:80

volumes:
  postgres-db: